apiVersion: apps/v1
kind: Deployment
metadata:
  name: capestone-deploy
  labels:
    app: capstone_app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone_app
  template:
    metadata:
      labels:
        app: capstone_app
    spec:
      containers:
      - name: container-mvn-container
        image: ashdoc123/banking-eta-app:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: bankingnp
  labels:
    app: capstone_app
spec:
  selector:
    app: capstone_app

  type: NodePort
  ports:
  - nodePort: 31003
    port: 8081
    targetPort: 8081
