apiVersion: v1
kind: Service
metadata:
  name: maven-app-service
spec:
  selector:
    app: maven-app
  ports:
  - protocol: TCP
    port: 8080        # service port (cluster-internal)
    targetPort: 8081  # <-- fix, matches Tomcat
    nodePort: 30080   # external port
  type: NodePort
